#!/bin/bash  
# checks if given arguments are set in the environment. returns 1 if at least one argument is not set

# checks if user is root. returns 1 if hes not root
STATE=0
[ "$EUID" -ne 0 ] && >&2 echo "Please run as root" && STATE=1

for ARG in "$@"; do
    [ "$ARG" ] || { >&2 echo "Environment not set, aborting" && exit 1; }
done

exit $STATE
