package de.toscana.transformator.executor;

import com.jcraft.jsch.JSchException;

import java.io.File;

/**
 * Interface of an Executor. It provides functions that are used
 * to upload the model and execute specific scripts of this model.
 *
 * @author mklopp
 */
public interface Executor {

    /**
     * executes the script on the machine
     *
     * @param script expects /nodename/scriptname
     * @return the output generated by running given script on target
     */
    String executeScript(String script) throws JSchException;

    /**
     * Uploads the file to the machine and unzips it
     *
     * @param file expects a .zip file
     * @return the output generated by running given script on target
     */
    String uploadAndUnzipZip(File file) throws JSchException;

    /**
     * Begins a ssh connection
     * return true if successful, else false
     */
    boolean connect();

    /**
     * Closes the current ssh connection
     */
    void close();

}
