#!/bin/bash
IP=$1
[ "$IP" ] && echo $IP > server.cnf || IP=$(cat server.cnf)
TARGET="ubuntu@$IP"

# copy files
ssh $TARGET "sudo apt update && sudo apt -y upgrade"
ssh $TARGET "rm -rf simple-app test"
scp -r simple-app $TARGET:.
scp -r util $TARGET:.
scp -r test $TARGET:.
ssh $TARGET 'sudo mv $HOME/util/* /usr/local/bin'

# fixing environment
ssh $TARGET 'echo set -o vi >> $HOME/.bashrc'  # some bash luxury

ssh $TARGET 'sudo $HOME/test/create'
