#!/bin/bash  
toscalite-checkenv
[ $? -eq 0 ] || exit 1

OLD_DIR=$PWD

# variables
# these are used in called scripts (therefore need for export!)
export DBMACHINE_IP=127.0.0.1

export MYSQL_ROOTPASSWORD=godpass
export MYSQL_PORT=3306

export PHPAPP_APP="phpapp.zip"

export DATABASE_DATABASENAME=awesomedb 
export DATABASE_USER=user
export DATABASE_PASSWORD=pass
export DATABASE_DATABASESCHEMA="createdb.sql"

# setup mysql
cd $HOME/simple-app/mysql
./create 
./start
# setup database
cd $HOME/simple-app/database
./create
# setup apache
cd $HOME/simple-app/apache
./create
./start
#setup php
cd $HOME/simple-app/php
./create

#setup php-app
cd $HOME/simple-app/phpapp
./create

#setup db connect
cd $HOME/simple-app/relationships
./dbconnect

cd $OLD_DIR
